### Exercise 1

1. Make a `ndarray` of size 10 with the shape (2,3,4,5).
2. Get the first 3 numbers from the inner most array

In [2]:
import numpy as np

In [4]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[5, 8, 2, 4, 6],
         [9, 2, 5, 5, 5],
         [8, 7, 0, 0, 8],
         [4, 4, 8, 4, 8]],

        [[0, 9, 6, 8, 4],
         [4, 3, 9, 4, 7],
         [9, 0, 6, 9, 4],
         [8, 2, 9, 4, 5]],

        [[5, 6, 4, 3, 1],
         [8, 8, 9, 9, 7],
         [1, 7, 2, 3, 6],
         [3, 1, 4, 9, 6]]],


       [[[6, 9, 2, 8, 2],
         [3, 4, 9, 3, 5],
         [6, 6, 3, 1, 4],
         [4, 9, 8, 6, 6]],

        [[8, 2, 5, 2, 5],
         [2, 5, 9, 4, 0],
         [5, 3, 1, 5, 8],
         [8, 3, 9, 3, 1]],

        [[9, 9, 2, 4, 8],
         [5, 4, 6, 5, 8],
         [4, 0, 6, 1, 4],
         [8, 8, 2, 3, 2]]]], dtype=int32)

In [5]:
a4[:, :, :, :2]

array([[[[5, 8],
         [9, 2],
         [8, 7],
         [4, 4]],

        [[0, 9],
         [4, 3],
         [9, 0],
         [8, 2]],

        [[5, 6],
         [8, 8],
         [1, 7],
         [3, 1]]],


       [[[6, 9],
         [3, 4],
         [6, 6],
         [4, 9]],

        [[8, 2],
         [2, 5],
         [5, 3],
         [8, 3]],

        [[9, 9],
         [5, 4],
         [4, 0],
         [8, 8]]]], dtype=int32)

# Exercise 1
## Nut Butter Store Sales

In [1]:
import pandas as pd
import numpy as np

In [4]:
almond_butter = pd.Series([2, 9, 11, 13, 15])
peanut_butter = pd.Series([7, 4, 14, 13, 18])
cashew_butter = pd.Series([1, 16, 18, 16, 9])
col1 = pd.Series(["Mon", "Tues", "Wed", "Thurs", "Fri"])

nut_butter_sales_main = pd.DataFrame({
    "": col1,
    "Almond butter": almond_butter,
    "Peanut butter": peanut_butter,
    "Cashew butter": cashew_butter,
})

nut_butter_sales_price = pd.DataFrame({
    "": ["Price"],
    "Almond butter": [10],
    "Peanut butter": [8],
    "Cashew butter": [12]
})

In [11]:
sales_array = np.array([[ 2,  7,  1],
                        [ 9,  4, 16],
                        [11, 14, 18],
                        [13, 13, 16],
                        [15, 18,  9]])
nut_butter_sales_main = pd.DataFrame(sales_array,
                                     index = ["Mon", "Tue", "Wed", "Thurs", "Fri"],
                                     columns = ["Almond butter", "Peanut butter", "Cashew butter"])

price_array = np.array([[10, 8, 12]])

nut_butter_sales_price = pd.DataFrame(price_array,
                                      index = ["Price"],
                                      columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [14]:
nut_butter_sales_main, nut_butter_sales_main.shape

(       Almond butter  Peanut butter  Cashew butter
 Mon                2              7              1
 Tue                9              4             16
 Wed               11             14             18
 Thurs             13             13             16
 Fri               15             18              9,
 (5, 3))

In [15]:
nut_butter_sales_price, nut_butter_sales_price.shape

(       Almond butter  Peanut butter  Cashew butter
 Price             10              8             12,
 (1, 3))

In [30]:
total = np.dot(nut_butter_sales_price, nut_butter_sales_main.T)
total

array([[ 88, 314, 438, 426, 402]])

In [18]:
nut_butter_sales_main["Total($)"] = total

In [19]:
nut_butter_sales_main

Almond butter  Peanut butter  Cashew butter  Total($)
Mon                2              7              1        88
Tue                9              4             16       314
Wed               11             14             18       438
Thurs             13             13             16       426
Fri               15             18              9       402

# Module exercises

### 1. Import NumPy as its abbreviation 'np'

In [1]:
import numpy as np

### Create a 1-dimensional NumPy array using np.array()

In [5]:
a1 = np.array([1, 2, 3])
a1

(array([1, 2, 3]), 1)

### Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)

In [9]:
a1.shape

(3,)

In [10]:
a1.ndim

1

In [11]:
a1.dtype

dtype('int64')

In [12]:
a1.size

3

In [14]:
type(a1)

numpy.ndarray

### Create a 2-dimensional NumPy array using np.array()

In [6]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2, a2.ndim

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 2)

### Attributes of 1-dimensional array (shape, `number of dimensions, data type, size and type)

In [15]:
a2.shape

(2, 3)

In [16]:
a2.ndim

2

In [17]:
a2.dtype

dtype('float64')

In [18]:
a2.size

6

In [19]:
type(a2)

numpy.ndarray

### Create a 3-dimensional Numpy array using np.array()

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                 [10, 11, 12]]])
a3, a3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 3)

### Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)

In [20]:
a3.shape

(2, 2, 3)

In [21]:
a2.ndim

2

In [23]:
a2.dtype

dtype('float64')

In [24]:
a2.size

6

In [25]:
type(a2)

numpy.ndarray

### Import pandas and create a DataFrame out of one of the arrays you've created

In [26]:
import pandas as pd

In [30]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [31]:
df = pd.DataFrame(a2,
                 index = ['A', 'B'],
                 columns = [1, 2, 3])
df

1    2    3
A  1.0  2.0  3.3
B  4.0  5.0  6.5

### Create an array of shape (10, 2) with only ones

In [34]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Create an array of shape (7, 2, 3) of only zeros

In [35]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Create an array within a range of 0 and 100 with step 3

In [40]:
array = np.arange(0,100, 3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### Create a random array with numbers between 0 and 10 of size (7, 2)

In [53]:
np.random.randint(10, size = (7,2))

array([[1, 3],
       [8, 1],
       [9, 8],
       [9, 4],
       [1, 3],
       [6, 7],
       [2, 0]], dtype=int32)

### Create a random array of floats between 0 & 1 of shape (3, 5)

In [52]:
np.random.random((3,5))

array([[0.00706631, 0.02306243, 0.52477466, 0.39986097, 0.04666566],
       [0.97375552, 0.23277134, 0.09060643, 0.61838601, 0.38246199],
       [0.98323089, 0.46676289, 0.85994041, 0.68030754, 0.45049925]])

### Set the random seed to 42

In [50]:
np.random.seed(42)

### Create a random array of numbers between 0 & 10 of size (4, 6)

In [51]:
np.random.randint(10, size = (4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

### Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable

In [54]:
random_array = np.random.randint(10, size = (3, 7))
random_array

array([[3, 1, 7, 3, 1, 5, 5],
       [9, 3, 5, 1, 9, 1, 9],
       [3, 7, 6, 8, 7, 4, 1]], dtype=int32)

### Find the unique numbers in the array you just created

In [55]:
np.unique(random_array)

array([1, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

### Find the 0'th index of the latest array you created

In [56]:
random_array[0]

array([3, 1, 7, 3, 1, 5, 5], dtype=int32)

### Get the first 2 rows of latest array you created

In [58]:
random_array[:2]

array([[3, 1, 7, 3, 1, 5, 5],
       [9, 3, 5, 1, 9, 1, 9]], dtype=int32)

### Get the first 2 values of the first 2 rows of the latest array


In [59]:
random_array[:2, :2]

array([[3, 1],
       [9, 3]], dtype=int32)

### Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables

In [62]:
random_array = np.random.randint(10, size = (3, 5))
ones = np.ones((3, 5))

In [63]:
random_array

array([[4, 7, 9, 8, 8],
       [0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0]], dtype=int32)

In [64]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Add the two arrays together

In [65]:
random_array + ones

array([[ 5.,  8., 10.,  9.,  9.],
       [ 1.,  9.,  7.,  9.,  8.],
       [ 1.,  8.,  8.,  3.,  1.]])

### Create another array of ones of shape (5, 3)

In [71]:
ones1 = np.ones((5, 3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Try add the array of ones and the other most recent array together

In [72]:
ones + ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

### Create another array of ones of shape (3, 5)

In [73]:
ones2 = np.ones((3, 5))
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Subtract the new array of ones from the other most recent array

In [77]:
random_array - ones2

array([[ 3.,  6.,  8.,  7.,  7.],
       [-1.,  7.,  5.,  7.,  6.],
       [-1.,  6.,  6.,  1., -1.]])

### Multiply the ones array with the latest array

In [78]:
ones * random_array

array([[4., 7., 9., 8., 8.],
       [0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.]])

### Take the latest array to the power of 2 using '**'

In [82]:
random_array ** 2

array([[16, 49, 81, 64, 64],
       [ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0]], dtype=int32)

### Do the same thing with np.square()

In [84]:
np.square(random_array)

array([[16, 49, 81, 64, 64],
       [ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0]], dtype=int32)

### Find the mean of the latest array using np.mean()

In [85]:
np.mean(random_array)

np.float64(5.4)

### Find the maximum of the latest array using np.max()

In [86]:
np.max(random_array)

np.int32(9)

### Find the minimum of the latest array using np.min()

In [87]:
np.min(random_array)

np.int32(0)

### Find the standard deviation of the latest array

In [88]:
np.std(random_array)

np.float64(3.1790984046843636)

### Find the variance of the latest array

In [89]:
np.var(random_array)

np.float64(10.106666666666666)

### Reshape the latest array to (3, 5, 1)

In [91]:
np.reshape(random_array, (3, 5, 1))

array([[[4],
        [7],
        [9],
        [8],
        [8]],

       [[0],
        [8],
        [6],
        [8],
        [7]],

       [[0],
        [7],
        [7],
        [2],
        [0]]], dtype=int32)

### Transpose the latest array

In [92]:
np.transpose(random_array)

array([[4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2],
       [8, 7, 0]], dtype=int32)

### Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)

In [93]:
random_array_1 = np.random.randint(10, size = (3,3))
random_array_2 = np.random.randint(10, size = (3, 2))

In [94]:
random_array_1

array([[7, 2, 2],
       [0, 4, 9],
       [6, 9, 8]], dtype=int32)

In [95]:
random_array_2

array([[6, 8],
       [7, 1],
       [0, 6]], dtype=int32)

### Perform a dot product on the two newest arrays you created

In [96]:
np.dot(random_array_1, random_array_2)

array([[ 56,  70],
       [ 28,  58],
       [ 99, 105]], dtype=int32)

### Create two arrays of random integers between 0 to 10 both of size (4, 3)

In [98]:
random_array_1 = np.random.randint(10, size=(4, 3))
random_array_1

array([[4, 9, 6],
       [6, 8, 9],
       [9, 2, 6],
       [0, 3, 3]], dtype=int32)

In [99]:
random_array_2 = np.random.randint(10, size = (4, 3))
random_array_2

array([[4, 6, 6],
       [3, 6, 2],
       [5, 1, 9],
       [8, 4, 5]], dtype=int32)

### Perform a dot product on the two newest arrays you created

In [100]:
np.dot(random_array_1, random_array_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

### Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both

In [102]:
random_array_2 = random_array_2.T

In [103]:
np.dot(random_array_1, random_array_2)

array([[106,  78,  83,  98],
       [126,  84, 119, 125],
       [ 84,  51, 101, 110],
       [ 36,  24,  30,  27]], dtype=int32)

### Create two arrays of random integers between 0 & 10 of the same shape and save them to variables

In [104]:
a1 = np.random.randint(10, size = (2, 3))
a1

array([[3, 9, 6],
       [8, 6, 0]], dtype=int32)

In [105]:
a2 = np.random.randint(10, size = (2,3))
a2

array([[0, 8, 8],
       [3, 8, 2]], dtype=int32)

### Compare the two arrays with '>'

In [106]:
a1>a2

array([[ True,  True, False],
       [ True, False, False]])

### Compare the two arrays with '>='

In [107]:
a1>=a2

array([[ True,  True, False],
       [ True, False, False]])

### Find which elements of the first array are greater than 7

In [108]:
a1>7

array([[False,  True, False],
       [ True, False, False]])

### Which parts of each array are equal? (try using '==')

In [109]:
a1 == a2

array([[False, False, False],
       [False, False, False]])

### Sort one of the arrays you just created in ascending order

In [110]:
np.sort(a1)

array([[3, 6, 9],
       [0, 6, 8]], dtype=int32)

In [111]:
np.sort(a2)

array([[0, 8, 8],
       [2, 3, 8]], dtype=int32)

### Sort the indexes of one of the arrays you just created

In [112]:
np.argsort(a1)

array([[0, 2, 1],
       [2, 1, 0]])

In [113]:
np.argsort(a2)

array([[0, 1, 2],
       [2, 0, 1]])

### Find the index with the maximum value in one of the arrays you've created

In [114]:
np.argmax(a1)

np.int64(1)

### Find the index with the minimum value in one of the arrays you've created

In [115]:
np.argmin(a1)

np.int64(5)

###  Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created

In [116]:
np.argmax(a1, axis = 1)

array([1, 0])

### Find the indexes with the minimum values across the 0th axis (axis=0) of one of the arrays you created

In [117]:
np.argmin(a1, axis = 0)

array([0, 1, 1])

### Create an array of normally distributed random numbers

In [118]:
normal_array = np.random.randn(10)
normal_array

array([ 0.00511346, -0.23458713, -1.41537074, -0.42064532, -0.34271452,
       -0.80227727, -0.16128571,  0.40405086,  1.8861859 ,  0.17457781])

In [119]:
np.std(normal_array)

np.float64(0.8180198457414615)

In [121]:
np.mean(normal_array)

np.float64(-0.09069526681059495)

### Create an array with 10 evenly spaced numbers between 1 and 100

In [120]:
evenly_spaced_array = np.linspace(1, 100, 10)

print(evenly_spaced_array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
